
development:
  adapter: postgresql
  encoding: unicode
  database: water_deposit_development
  pool: 5
  username: wonyoungso
  host: localhost
  password:


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: water_deposit_test
  pool: 5
  username: wonyoungso
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: water_deposit_production
  pool: 5
  username: <%= ENV['WONYOUNGSO_PGSQL_ID'] %>
  password: <%= ENV['WONYOUNGSO_PGSQL_PASSWD'] %>
